In [ ]:
#KNeighnorsRegressor
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor


In [ ]:
df = pd.read_csv('insurance.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [ ]:
df['sex'] = df['sex'].map({'female': 0, 'male': 1})

In [ ]:
df.head()

age  sex     bmi  children smoker     region      charges
0   19    0  27.900         0    yes  southwest  16884.92400
1   18    1  33.770         1     no  southeast   1725.55230
2   28    1  33.000         3     no  southeast   4449.46200
3   33    1  22.705         0     no  northwest  21984.47061
4   32    1  28.880         0     no  northwest   3866.85520

In [ ]:
df['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [ ]:
df['smoker'] = df['smoker'].map({'no': 0, 'yes': 1})

In [ ]:
df.head()

age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [ ]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
df['region'] = df['region'].map({'southwest':0,'southeast':1,'northwest':2,'northwest':3})

In [ ]:
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1     0.0  16884.92400
1   18    1  33.770         1       0     1.0   1725.55230
2   28    1  33.000         3       0     1.0   4449.46200
3   33    1  22.705         0       0     3.0  21984.47061
4   32    1  28.880         0       0     3.0   3866.85520

In [ ]:
df.shape

(1338, 7)

In [ ]:
df.isna().sum()

age           0
sex           0
bmi           0
children      0
smoker        0
region      324
charges       0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
X = df[['age', 'sex', 'bmi', 'children', 'smoker', 'region']]
y = df['charges']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
knn = KNeighborsRegressor(n_neighbors=5)

In [ ]:
knn.fit(X_train,y_train)

KNeighborsRegressor()

In [ ]:
knn.predict([[19,0,27.900,0,	1,	0.0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([10867.7166])

In [ ]:
knn.score(X_test,y_test)

-0.022007749126964127

In [ ]:
dfn = pd.read_csv('insurance.csv')

In [ ]:
dfn.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
dfn = pd.read_csv('insurance.csv')

In [ ]:
dfn.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
dfn.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
encoder = OneHotEncoder(sparse=False)
dfn['sex'] = encoder.fit_transform(dfn[['sex']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
encoder = OneHotEncoder(sparse=False)
dfn['sex'] = encoder.fit_transform(dfn[['sex']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
dfn['smoker'] = encoder.fit_transform(dfn[['smoker']])
dfn['region'] = encoder.fit_transform(dfn[['region']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
dfn.head()

age  sex     bmi  children  smoker  region      charges
0   19  0.0  27.900         0     0.0     0.0  16884.92400
1   18  1.0  33.770         1     1.0     0.0   1725.55230
2   28  1.0  33.000         3     1.0     0.0   4449.46200
3   33  1.0  22.705         0     1.0     0.0  21984.47061
4   32  1.0  28.880         0     1.0     0.0   3866.85520

In [ ]:
dfn.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
X = dfn[['age', 'sex', 'bmi', 'children', 'smoker', 'region']]
y = dfn['charges']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train

age  sex     bmi  children  smoker  region
560    46  0.0  19.950         2     1.0     0.0
1285   47  0.0  24.320         0     1.0     1.0
1142   52  0.0  24.860         0     1.0     0.0
969    39  0.0  34.320         5     1.0     0.0
486    54  0.0  21.470         3     1.0     0.0
...   ...  ...     ...       ...     ...     ...
1095   18  0.0  31.350         4     1.0     1.0
1130   39  0.0  23.870         5     1.0     0.0
1294   58  1.0  25.175         0     1.0     1.0
860    37  0.0  47.600         2     0.0     0.0
1126   55  1.0  29.900         0     1.0     0.0

[1070 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.47222651, -1.0246016 , -1.75652513,  0.73433626,  0.50874702,
        -0.57663083],
       [ 0.54331294, -1.0246016 , -1.03308239, -0.91119211,  0.50874702,
         1.73421182],
       [ 0.8987451 , -1.0246016 , -0.94368672, -0.91119211,  0.50874702,
        -0.57663083],
       ...,
       [ 1.3252637 ,  0.97598911, -0.89153925, -0.91119211,  0.50874702,
         1.73421182],
       [-0.16755139, -1.0246016 ,  2.82086429,  0.73433626, -1.96561348,
        -0.57663083],
       [ 1.1120044 ,  0.97598911, -0.10932713, -0.91119211,  0.50874702,
        -0.57663083]])

In [ ]:
dfn['charges'][560]

9193.8385

In [ ]:
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsRegressor()

In [ ]:
knn.predict([[0.47222651,  1.0246016 , -1.75652513,  0.73433626,  0.50874702,
        -0.57663083]])

array([12577.277088])

In [ ]:
knn.score(X_train,y_train) #0 to 1

0.8701703168118499

In [ ]:
21/20.25

1.037037037037037

In [ ]:
22/20.25

1.0864197530864197

In [ ]:
23/20.25

1.1358024691358024

In [ ]:
15/20.25

0.7407407407407407